// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://khdgcwkbfeakmqbuzahf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsImtpZCI6IjJ6T0NYQ1c2T3pTVmFKRV…xzZX0.H3hm00a49RJkfi9Ngjk8dxfKQj_SNLHs6mgl0_6qmww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true, // Ensure session persistence across browser sessions
    autoRefreshToken: true, // Automatically refresh expired tokens
    detectSessionInUrl: true, // Detect session from URL for OAuth callbacks
  }
});